source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/MyGitHubModule/MMSpecs.git'
platform :ios, ‘9.0’

target “MyGitHub” do
pod 'Masonry', '~> 1.1.0’
pod 'YTKNetwork', '~> 2.0.4’
pod 'SDWebImage', '~> 4.3.3’
pod 'IQKeyboardManager', '~> 5.0.8’
pod 'MJRefresh', '~> 3.1.15.3’
pod 'YYKit', '~> 1.0.9’
pod 'RTRootNavigationController', '~> 0.6.6’
pod 'ReactiveCocoa', '~> 2.5’
pod 'lottie-ios', '~> 2.5.0’
pod 'MMNetwork', '~> 0.0.1’
end
